version: '3.4'
services:
  cached-certificate-operator:
    image: cached-certificate-operator
    container_name: cached-certificate-operator
    entrypoint: /bin/bash
    build:
      context: ./
      dockerfile: Dockerfile
      network: host
    stdin_open: true
    tty: true
